### ISSUE TITLE
Proper integration doc

### ISSUE THREAD

**Issue by sahilpaudel-pe** [loopsocial/cassandrax#12]
Hi there,

This repo seems promising and I find this very much what I wanted.

Can you please take some time and add proper documentation on how can I or someone would integrate in there existing phoenix/elixir application.

When I read readme.md its bit difficult to understand like how `Cassandrax.MyConn` works.

Thank you 👍

**Comment by tdtadeu** [comment]
Hey @sahilpaudel-pe!

Thanks for the feedback, documentation is certainly something we need to improve and I'll put some effort into making some things more clear for developers who want to integrate it with their existing phoenix apps.

Btw, did you read our docs already? https://hexdocs.pm/cassandrax/Cassandrax.html

If you have any specific questions, I'd be more than happy to help you out.

**Comment by tdtadeu** [comment]
@sahilpaudel-pe I updated the `README` and added some phoenix examples as well.
