### ISSUE TITLE
Can I use Xandra and Triton in cassandrax

### ISSUE THREAD

**Issue by Human-bio** [loopsocial/cassandrax#16]

**Comment by tdtadeu** [comment]
Hello!

Cassandrax already uses Xandra to establish the connection with the cluster as well as prepare and execute CQL commands on it.

Regarding Triton, I don't know exactly how you'd want to use it with Cassandrax. Could you please elaborate on that?

**Comment by tdtadeu** [comment]
I'll considered this answered for now.
