### ISSUE TITLE
Missing cassandra ecto adapter

### ISSUE THREAD

**Issue by shirokovnv** [loopsocial/cassandrax#24]
Hello!

Can you suggest how to define Ecto Repo for migrations and do we need to use some kind of Cassandra Ecto Adapter for it ?

Thanks.

**Comment by tdtadeu** [comment]
Hey @shirokovnv, although far from ideal, right now what I'd suggest is you use an existing `Ecto.Repo` (if you have one) to run your cassandra migrations, much like what [@cjbottaro](https://elixirforum.com/u/cjbottaro) suggested in your thread [Migration tools for cassandra](https://elixirforum.com/t/migration-tools-for-cassandra/50119/3) and it is what we describe in the readme.

**Comment by shirokovnv** [comment]
Thank you for the answer. I will close the issue.
